In [1]:
import kaggle 
! kaggle datasets download -d girumwondemagegn/dataset-for-renewable-energy-systems

Dataset URL: https://www.kaggle.com/datasets/girumwondemagegn/dataset-for-renewable-energy-systems
License(s): Apache 2.0
Downloading dataset-for-renewable-energy-systems.zip to d:\artificial intelligence\sql projects\green energy

  0%|          | 0.00/853k [00:00<?, ?B/s]
100%|██████████| 853k/853k [00:01<00:00, 619kB/s]
100%|██████████| 853k/853k [00:01<00:00, 619kB/s]

In [1]:
import zipfile as zp
zip_ref = zp.ZipFile('dataset-for-renewable-energy-systems.zip')
zip_ref.extractall()
zip_ref.close()

In [1]:
import pandas as pd
df = pd.read_csv('energy_dataset_.csv', index_col=False)
df

,Type_of_Renewable_Energy,Installed_Capacity_MW,Energy_Production_MWh,Energy_Consumption_MWh,Energy_Storage_Capacity_MWh,Storage_Efficiency_Percentage,Grid_Integration_Level,Initial_Investment_USD,Funding_Sources,Financial_Incentives_USD,GHG_Emission_Reduction_tCO2e,Air_Pollution_Reduction_Index,Jobs_Created
0,4,93.423205,103853.2206,248708.4892,2953.248771,89.887562,4,4.732248e+08,1,9.207772e+06,6663.816572,81.742461,1366
1,4,590.468942,190223.0649,166104.1642,5305.174042,84.403343,4,1.670697e+08,2,1.685101e+06,30656.049820,78.139042,1743
2,1,625.951142,266023.4824,424114.6308,2620.192622,60.498249,2,8.463610e+07,2,5.111813e+06,1749.613759,8.461296,363
3,1,779.998728,487039.5296,308337.7316,1925.250307,86.897861,3,3.967690e+08,2,4.805902e+06,43233.237820,8.402441,2821
4,3,242.106837,482815.0856,360437.7705,3948.945383,70.949351,2,3.574413e+07,1,1.668601e+07,14858.662760,28.822867,2583
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,3,745.032555,280007.5738,230544.8268,4351.687893,90.791405,4,3.484136e+08,2,1.558508e+07,25234.911810,78.923200,1452
14996,1,15.187023,377340.5803,358547.3589,6792.194696,78.252040,4,2.560179e+08,3,6.866618e+06,15762.519790,54.982974,2598
14997,3,877.539059,480497.3920,214441.6719,4588.725297,58.282928,1,1.300112e+08,2,3.837764e+06,44597.809410,43.915897,2713
14998,7,551.264716,436383.1694,137043.8713,7251.144215,73.573666,2,3.334831e+08,2,5.347706e+06,34363.858000,4.877145,2128
14999,3,863.421803,314014.3005,124461.9178,7366.166362,86.868893,4,2.989825e+08,2,1.832534e+07,27193.217600,50.559075,1871

In [2]:
df.dtypes

Type_of_Renewable_Energy           int64
Installed_Capacity_MW            float64
Energy_Production_MWh            float64
Energy_Consumption_MWh           float64
Energy_Storage_Capacity_MWh      float64
Storage_Efficiency_Percentage    float64
Grid_Integration_Level             int64
Initial_Investment_USD           float64
Funding_Sources                    int64
Financial_Incentives_USD         float64
GHG_Emission_Reduction_tCO2e     float64
Air_Pollution_Reduction_Index    float64
Jobs_Created                       int64
dtype: object

In [3]:
df.isna().sum()

Type_of_Renewable_Energy         0
Installed_Capacity_MW            0
Energy_Production_MWh            0
Energy_Consumption_MWh           0
Energy_Storage_Capacity_MWh      0
Storage_Efficiency_Percentage    0
Grid_Integration_Level           0
Initial_Investment_USD           0
Funding_Sources                  0
Financial_Incentives_USD         0
GHG_Emission_Reduction_tCO2e     0
Air_Pollution_Reduction_Index    0
Jobs_Created                     0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df['Initial_Investment_USD'] = df['Initial_Investment_USD'].apply(lambda x: '{:.0f}'.format(x) if pd.notnull(x) else x)
df['Financial_Incentives_USD'] = df['Financial_Incentives_USD'].apply(lambda x: '{:.0f}'.format(x) if pd.notnull(x) else x)

In [8]:
df

,Type_of_Renewable_Energy,Installed_Capacity_MW,Energy_Production_MWh,Energy_Consumption_MWh,Energy_Storage_Capacity_MWh,Storage_Efficiency_Percentage,Grid_Integration_Level,Initial_Investment_USD,Funding_Sources,Financial_Incentives_USD,GHG_Emission_Reduction_tCO2e,Air_Pollution_Reduction_Index,Jobs_Created
0,4,93.423205,103853.22,248708.49,2953.25,89.89,4,473224764,1,9207772,6663.82,81.74,1366
1,4,590.468942,190223.06,166104.16,5305.17,84.40,4,167069722,2,1685101,30656.05,78.14,1743
2,1,625.951142,266023.48,424114.63,2620.19,60.50,2,84636100,2,5111813,1749.61,8.46,363
3,1,779.998728,487039.53,308337.73,1925.25,86.90,3,396768982,2,4805902,43233.24,8.40,2821
4,3,242.106837,482815.09,360437.77,3948.95,70.95,2,35744128,1,16686014,14858.66,28.82,2583
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,3,745.032555,280007.57,230544.83,4351.69,90.79,4,348413618,2,15585079,25234.91,78.92,1452
14996,1,15.187023,377340.58,358547.36,6792.19,78.25,4,256017850,3,6866618,15762.52,54.98,2598
14997,3,877.539059,480497.39,214441.67,4588.73,58.28,1,130011205,2,3837764,44597.81,43.92,2713
14998,7,551.264716,436383.17,137043.87,7251.14,73.57,2,333483073,2,5347706,34363.86,4.88,2128
14999,3,863.421803,314014.30,124461.92,7366.17,86.87,4,298982500,2,18325342,27193.22,50.56,1871

In [ ]:
df['Installed_Capacity_MW'] = df['Installed_Capacity_MW'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['Energy_Production_MWh'] = df['Energy_Production_MWh'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['Energy_Consumption_MWh'] = df['Energy_Consumption_MWh'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['Energy_Storage_Capacity_MWh'] = df['Energy_Storage_Capacity_MWh'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['Storage_Efficiency_Percentage'] = df['Storage_Efficiency_Percentage'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['GHG_Emission_Reduction_tCO2e'] = df['GHG_Emission_Reduction_tCO2e'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)
df['Air_Pollution_Reduction_Index'] = df['Air_Pollution_Reduction_Index'].apply(lambda x: '{:.2f}'.format(x) if pd.notnull(x) else x)

In [35]:
df

,Type_of_Renewable_Energy,Installed_Capacity_MW,Energy_Production_MWh,Energy_Consumption_MWh,Energy_Storage_Capacity_MWh,Storage_Efficiency_Percentage,Grid_Integration_Level,Initial_Investment_USD,Funding_Sources,Financial_Incentives_USD,GHG_Emission_Reduction_tCO2e,Air_Pollution_Reduction_Index,Jobs_Created,Funding_Sources
0,Geothermal,93.42,103853.22,248708.49,2953.25,89.89,Isolated Microgrid,473224764,Government,9207772,6663.82,81.74,1366,Government
1,Geothermal,590.47,190223.06,166104.16,5305.17,84.40,Isolated Microgrid,167069722,Private,1685101,30656.05,78.14,1743,Private
2,Solar,625.95,266023.48,424114.63,2620.19,60.50,Partially Integrated,84636100,Private,5111813,1749.61,8.46,363,Private
3,Solar,780.00,487039.53,308337.73,1925.25,86.90,Minimal Integration,396768982,Private,4805902,43233.24,8.40,2821,Private
4,Hydroelectric,242.11,482815.09,360437.77,3948.95,70.95,Partially Integrated,35744128,Government,16686014,14858.66,28.82,2583,Government
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,Hydroelectric,745.03,280007.57,230544.83,4351.69,90.79,Isolated Microgrid,348413618,Private,15585079,25234.91,78.92,1452,Private
14996,Solar,15.19,377340.58,358547.36,6792.19,78.25,Isolated Microgrid,256017850,Public-Private Partnership,6866618,15762.52,54.98,2598,Public-Private Partnership
14997,Hydroelectric,877.54,480497.39,214441.67,4588.73,58.28,Fully Integrated,130011205,Private,3837764,44597.81,43.92,2713,Private
14998,Wave,551.26,436383.17,137043.87,7251.14,73.57,Partially Integrated,333483073,Private,5347706,34363.86,4.88,2128,Private
14999,Hydroelectric,863.42,314014.30,124461.92,7366.17,86.87,Isolated Microgrid,298982500,Private,18325342,27193.22,50.56,1871,Private

In [12]:
df['Type_of_Renewable_Energy'].replace(1, 'Solar')

0            4
1            4
2        Solar
3        Solar
4            3
         ...
14995        3
14996    Solar
14997        3
14998        7
14999        3
Name: Type_of_Renewable_Energy, Length: 15000, dtype: object

In [17]:
df['Type_of_Renewable_Energy'] = df['Type_of_Renewable_Energy'].replace(
    {
        1 : 'Solar',
        2 : 'Wind',
        3 : 'Hydroelectric',
        4 : 'Geothermal',
        5 : "Biomass",
        6 : 'Tidal',
        7 : 'Wave'
    }
)

In [19]:
df['Grid_Integration_Level'] = df['Grid_Integration_Level'].replace(
    {
        1 : 'Fully Integrated',
        2 : 'Partially Integrated',
        3 : 'Minimal Integration',
        4 : 'Isolated Microgrid',
    }
)

In [21]:
df['Funding_Sources'].unique()

array([1, 2, 3], dtype=int64)

In [29]:
df['Funding_Sources'] = df['Funding_Sources'].replace(
    {
        1 : 'Government',
        2 : 'Private',
        3 : 'Public-Private Partnership'
    }
)

In [33]:
df.rename(columns= {'Funding_Sources\t' : 'Funding_Sources'}, inplace=True)

In [34]:
df.columns

Index(['Type_of_Renewable_Energy', 'Installed_Capacity_MW',
       'Energy_Production_MWh', 'Energy_Consumption_MWh',
       'Energy_Storage_Capacity_MWh', 'Storage_Efficiency_Percentage',
       'Grid_Integration_Level', 'Initial_Investment_USD', 'Funding_Sources',
       'Financial_Incentives_USD', 'GHG_Emission_Reduction_tCO2e',
       'Air_Pollution_Reduction_Index', 'Jobs_Created', 'Funding_Sources'],
      dtype='object')

In [36]:
df.to_csv("cleaned_energy_dataser.csv", index=False)